#!/bin/bash
#Bash interactive functions.
# Name me something hidden, like ".bashinterfuncs", and source me from .profile
# Copyright 2019 David C. Todd, License for use: GPL 2.0

wla ()
{
    : doc "Add email address to spamassassin white list."

    echo whitelist_from $1 >> ~/.spamassassin/user_prefs ;
}

nalias ()
{
    : doc "Add an alias to .alias (sourced in .profile), and the current session"
						       
    alias $1="$2" && echo "alias $1='$2'" >> ~/.alias
}

#find every file name starting with $1, get the part of its filename
#that starts after the first '.', then change the first part to $2.
# For instance, foo.bar, foo.baz, and foo.bar.baz
# $ ls
# foo.bar foo.baz foo.fum
# $ massmv foo pie
# $ ls
# pie.bar pie.baz pie.fum
massmv ()
{
    : doc "Rename files starting matching $1.* to $2 and the suffix from the old file."
	if (($# != 2)); then echo "must have two parameters"; return 1; fi
	for i in $1.*;
	  do
	  suf=`echo $i | cut -d . -f 2-`;
	  mv $i $2.$suf;
	done
}

uz ()
{
    : doc "Unzip a file into a (created?) directory called the filename minus .zip"
    
	dir=`basename $1 .zip`;
	mkdir $dir;
	mv $1 $dir;
	cd $dir;
	unzip $1;
	cd ..;
	ls -l $dir
}

les ()
{
    : doc "If the argument is a directory list it, otherwise less it."
	if (($# == 0)); then ls;
	elif /usr/bin/test -d $1; then ls $1;
	else less $1;
	fi
}
grwl ()
{
    : doc "Grep the spamassassin prefs file (which holds the whitelist)"
    grep $1 ~/.spamassassin/user_prefs
}

lsfunc ()
{
    : doc "List functions with docstrings, if there is a doc"
    : doc "If it has more than one line it'll look like this."
    declare -f | lsfun.py
}
